encoder_name: 'timm-efficientnet-b3'
encoder_weights: 'noisy-student'
in_features: 1536
workers: 28

chexpert_image_size: 384
chexpert_batch_size: 24
chexpert_init_lr: 0.00015
chexpert_epochs: 10

chest14_image_size: 384
chest14_batch_size: 24
chest14_init_lr: 0.0001
chest14_epochs: 15

aux_image_size: 384
aux_batch_size: 36
aux_init_lr: 0.0001
aux_epochs: 30
decoder: 'deeplabv3plus'
decoder_channels: 256
aux_mixup: False
aux_weight: 0.6
model_ema_decay: 0.997