encoder_name: 'timm-efficientnet-b3'
encoder_weights: 'noisy-student'
in_features: 1536
workers: 28

chexpert_image_size: 128
chexpert_batch_size: 48
chexpert_init_lr: 0.00015
chexpert_epochs: 1

chest14_image_size: 128
chest14_batch_size: 48
chest14_init_lr: 0.0001
chest14_epochs: 2

aux_image_size: 128
aux_batch_size: 64
aux_init_lr: 0.0001
aux_epochs: 2
decoder: 'deeplabv3plus'
decoder_channels: 256
aux_mixup: False
aux_weight: 0.6
model_ema_decay: 0.997