backbone_name: 'resnet200d'
in_features: 2048
workers: 8

chexpert_image_size: 512
chexpert_batch_size: 40
chexpert_init_lr: 0.0001
chexpert_epochs: 3

chest14_image_size: 512
chest14_batch_size: 40
chest14_init_lr: 0.0001
chest14_epochs: 5

aux_image_size: 768
aux_batch_size: 16
aux_init_lr: 0.0001
aux_epochs: 20
model_ema_decay: 0.997
